Map<String, String> stationCodes = {
  'Thrissur': 'TCR',
  'Kozhikode': 'CLT',
  'Thiruvananthapuram': 'TVC',
  'Aluva': 'AWY',
  'Kollam': 'QLN',
  'Kayamkulam': 'KYJ',
  'Shornur': 'SRR',
  'Ernakulam': 'ERN',
  'Kottayam': 'KTYM',
  'Alappuzha': 'ALLP',
  'Ottappalam': 'OTP',
  'Guruvayur': 'GUV',
  'Palakkad': 'PGTN',
};
